### ISSUE TITLE
Internal API does not return an extension value when file is unidentified

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#1126]
API does not return a value for extension when it is unidentified, it does in UI and cmd line DROID. Example attached. 
<img width="311" alt="Capture2" src="https://github.com/user-attachments/assets/fda11f9b-9611-4d2f-b37e-0cace3b9d931">
<img width="680" alt="Capture" src="https://github.com/user-attachments/assets/97475c55-eba2-4d93-8e19-b9be53425689">

**Comment by sparkhi** [comment]
Steps to reproduce:
1) Create a plain text file
2) Change its extension to be PDF

Such file is neither identified by signature nor by extension. Run such file through internal API and you will notice that the extension of he file is not reported

**Comment by sparkhi** [comment]
This is more complicated. If you look at this class `uk.gov.nationalarchives.droid.internal.api.ApiResult` you will notice that the class contains all the returned values, however when there is no successful identification, there is no ApiResult object at all, hence no other details too. 
I guess the best option is for the caller of the API to extract the extension from the request.

**Comment by steve-daly** [comment]
This behaviour is by design.  The API is asking DROID to identify the file format, and when it can't identify a format, it doesn't return an Identification Results object, as there is no valid identification result.  There's not a logical way of passing back the file extension in this case, as there is no valid IdentificationResults object for this to sit within.  

The DROID GUI and Command Line do a lot more than the API in terms of file metadata extraction, such as getting file size and generating checksums, which is beyond the scope of the API which just provides an interface into the format-detection feature of DROID.  

If a calling system needs to know the file extension of a filename then this should be extracted by simple string manipulation.
