### ISSUE TITLE
Ability to get and set maxBytes param using DROID CLI

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#215]
Request via Google Group - https://groups.google.com/forum/#!topic/droid-list/YiV7NQE2olk

**Comment by nishihatapalmer** [comment]
This is really wider than just max bytes to scan.  We really need to be able to pass any configurable profile property into the CLI.  

At present, we have to edit the profile properties in the GUI (not workable if you want to script different things) or use scripting hacks to edit the properties file just to control what the CLI does.

**Comment by nishihatapalmer** [comment]
A simple method might be to offer a command line option that allows particular properties to be set, as some kind of delimited string.  It might be a bit geeky vs. having dedicated command line options for each setting,, but it would provide a default capability for any configurable property.

**Comment by nishihatapalmer** [comment]
I'm having the issue of injecting runtime configuration into a new profile in some other work I'm doing.

When DROID initialises a profile, it reads configurable properties from the global config from the properties file in the profile working directory.  

It's not clear how to inject additional property overrides (or to specify another property file) given the way it's all initialized by Spring.  I guess there must be a way to inject runtime properties into the spring initialization...

**Comment by nishihatapalmer** [comment]
Right - I think the ProfileManager interface needs a new create method which takes sigs AND a set of properties to override any default profile properties.  The current method only lets you create a profile with sigs passed in (so all runtime configuration comes from default properties).

**Comment by nishihatapalmer** [comment]
I have a branch on my own fork which allows any profile properties to be set, either directly on the command line, or by specifying an alternate property file to use.

Still needs more testing, but can be seen here: https://github.com/nishihatapalmer/droid/tree/ProfileProperties

To override a profile property such as max bytes to scan, you specify it like this:

`droid -a "/home/user/Documents" -R -p "/home/user/docprofile.droid" -Pr "profile.maxBytesToScan=1024"`

If you have a lot of properties you want to override all the time, or different sets of properties you want to re-use, you can put them in a property file and tell DROID to use that:

`droid -a "/home/user/Documents" -R -p "/home/user/docprofile.droid" -Pf  "/home/user/my.properties"`

**Comment by nishihatapalmer** [comment]
One slightly annoying limitation of the current code is that a few properties are not set when a profile is created, but are rather used when it is opened (and taken from the global property file at that point).

All the normal profile properties like whether it processes archive files, or max bytes to scan can be set on creation.  These properties tend to be prefixed by "profile."  But there are other properties defined in the global property file too, like "database.durability".

These will still be taken from the global property file when the profile is actually opened, so they can't currently be overridden.  To fix that, we'd need the profile to remember all the properties it is given when created (not just the ones that directly affect the basic profile), so that they could be re-used when it is opened.  I've experimented with this, but my first attempt was quite ugly, so I've reverted to less invasive code which just lets basic profile properties to be set for the time being.

**Comment by nishihatapalmer** [comment]
I've submitted a PR here with the ability to set profile properties (but not to get them so far).

https://github.com/digital-preservation/droid/pull/407

**Comment by nishihatapalmer** [comment]
Propose this issue is closed - PR above allows setting max bytes.  Is there any demand for doing a "get"?  Which would only return what the profile default setting is (you can just look in the file or run DROID GUI and look at the default properties sheet).

**Comment by OliverHannan** [comment]
After investigation PR above https://github.com/digital-preservation/droid/pull/407 allows for original issue.
