### ISSUE TITLE
DROID doesn't have arbitrary container signature support, i.e. container matching doesn't seem match the container extraction formats

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#221]
I was experimenting with container signature files today to see if I could write a signature for a gzip packaged file and while I can make the container pattern match for a similarly structured ZIP file, it doesn't seem to be enough to add GZIP to the trigger PUIDs for DROID to be able to handle that (verified by trying the same container pattern in a zip container):

```
  <TriggerPuids>
    <TriggerPuid ContainerType="OLE2" Puid="fmt/111"/>
    <TriggerPuid ContainerType="ZIP" Puid="fmt/189"/>
    <TriggerPuid ContainerType="ZIP" Puid="x-fmt/263"/>
    <TriggerPuid ContainerType="GZIP" Puid="x-fmt/266"/>
  </TriggerPuids>
```

My use case was trying to identify RData inside GZip packages, e.g. from Dataverse: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y#

But because there are other issues with trying to write that signature, i.e. the path inside the zip is somewhat arbitrary, a more significant use-case might be required for this to be a more useful feature.

**Comment by anjackson** [comment]
It's been a while, but I thought GZipped files were handled as archives, to be opened and scanned recursively, rather than as containers? i.e. you should be able to ID `something-in-a-gz` as long as there's a sig for the `something`?

Also, IIRC, the container signatures rely on having some folder structure within the container format, which GZip doesn't have.

**Comment by Dclipsham** [comment]
I think there is an issue with DROID and arbitrary container support (and there's definitely a need to handle arbitrary filenames within containers - this applies e.g. to newer thumbs.db files that cannot currently be represented because of this limitation), but I'm not sure GZIP is the best use case? 

There are certain formats that do lend themselves to, even recommend compressing within GZIP - rdata being one where the default (but not only possible) output is GZIP. Gnumeric also (not yet in PRONOM but - https://help.gnome.org/users/gnumeric/stable/sect-files-overview.html.en), Scribus (https://www.nationalarchives.gov.uk/PRONOM/fmt/1091). Farbfeld (https://github.com/mcritchlow/farbfeld) gives BZ2 as an example but would also happily work with GZIP. 

In these examples is it not more desirable to give both ID - e.g. for the archival container and the file within? I see it as a distinct case from, say an OOXML file where the package is integral to the format

**Comment by nishihatapalmer** [comment]
I agree that gzip isn't a great use case for this, given it doesn't have paths inside it - it just compresses a single file.  

To answer Ross's original question about how to support new container formats, adding a known trigger format to the XML isn't enough on its own to enable container processing.  

You also have to create container identifier and identifier engine objects for that format and register them in the spring system (see the zip and ole2 examples and the spring-results.xml for examples).

**Comment by nishihatapalmer** [comment]
I think we can close this issue.

DROID does **not** have arbitrary container support, in the sense that any existing archive format can also be a container format with only configuration changes.  Note that OLE2 (which is a container format) is not an archive format.  So there isn't a 1-1 correspondence between them.

To add support for a new container format requires new code, even if the containing format is already a supported archive format.  It would be possible to add something like this, but it would involve a lot of change, and I honestly don't think the use-case warrants it.

**Comment by jcharlet** [comment]
@Dclipsham thoughts on that?

**Comment by Dclipsham** [comment]
agreed going to close the issue as each usecase needs handler. The presence of triggerPuids allows to to exclude scenarios (e.g. to say no OLE2 results), and I can see why it would _appear_ that arbitrary container support is possible but  can't see a viable way to achieving that. Potentially we could provide wording around container signature files that explains this.
