### ISSUE TITLE
full implementation of standard signature syntax in container signatures

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#237]
Container signatures don't currently work when providing certain valid binary signature patterns, e.g. either/or patterns (xx|xx) and inline wildcard ranges {0-4}. Current workarounds involve multiple signature blocks, which is unsatisfactory

**Comment by nishihatapalmer** [comment]
This is a consequence of the original split between PRONOM and DROID.   PRONOM itself compiles the binary signature syntax into a set of instructions to match sequences, with left and right fragments used for alternatives and wildcards.

What DROID really needs is a PRONOM syntax signature parser / compiler.  It won't be needed for binary signatures (since PRONOM is already doing this), but it is needed to enable the full DROID syntax for containers, since PRONOM doesn't get involved in compiling those.

I think this would be a really good idea.  It then frees DROID a hard PRONOM dependency.  If also applied to binary signatures, it would allow anyone to develop DROID signatures using the natural syntax, rather than having to become deep technical experts in how PRONOM works.

**Comment by nishihatapalmer** [comment]
I may have a go at writing this - I've done a lot of work on parsing and compiling in byteseek.  Unless someone else is already working on this?

**Comment by nishihatapalmer** [comment]
A longer term consequence of this would be PRONOM would no longer need to be able to process the signature syntax, just store the signature syntax.

This would make maintaining PRONOM cheaper, and allow the syntax to evolve independently of the registry used to manage the signatures.

It's clearly right that the tool which processes the signatures should decide how they need to be processed and compiled.  

In some cases, PRONOM already produces sub-optimal compilation.  There is already code in DROID to try to mitigate PRONOM's sub-optimal decisions!

**Comment by ross-spencer** [comment]
Long-day here, ultimately sounds like a good idea as a consumer of these. I think an impact on my work will be some minor changes to the [skeleton-suite](https://github.com/exponential-decay/pronom-archive-and-skeleton-test-suite) which as a tool helps keep PRONOM on its toes. Might be useful in your dev too Matt? I don't think TNA have incorporated into their base-code yet? But yeah, I think I'm doing a bit of interpretation of the natural syntax and then turning it into the original syntax, and then outputting the binary files. It will be nice to simplify a bit of that in future, and just keep legacy releases around for preservation's sake. The [signature-development-utility](http://www.nationalarchives.gov.uk/pronom/sigdev/index.htm) can only benefit if it just has to output what's on a form, into a useful signature file that can be consumed by a DROID or a Siegfried.

**Comment by nishihatapalmer** [comment]
I've had a play with this today.  I have an prototype  parser / compiler for droid regular expressions that produces ByteSequence objects from the droid syntax.

The next problem is how these things are represented in the DROID xml.  Having spent a bit of time on this, the DROID expressions need to be represented as an attribute of the ByteSequence object.  This is because of the way the XML parser instantiates objects.  If we use an element under ByteSequences, it's already too late to modify the parent ByteSequence object.

So the proposal would be to have an attribute of ByteSequence containing the droid regular expression.  For example:

<ByteSequence reference="BOFoffset" expression="01 02 03 [!03:1F] 04" />

**Comment by nishihatapalmer** [comment]
Another consideration is not interfering with the current processing pathways when parsing the DROID signature files. 

The code currently treats the results of parsing XML as the very objects that perform the matching.  This causes lots of problems - the matching objects have to exactly match the XML structure used to define them.  Alternative ways of defining signatures become difficult (they ultimately have to boil down to the XML structure).

A better longer term solution would be to  apply standard compiler theory, and separate the structure of a particular file format used to define signatures from the objects used to match them. Parsers should create an abstract syntax tree (the meaning of parsing a particular format), and compilers should take an abstract syntax tree and make the right matching objects from them.

**Comment by nishihatapalmer** [comment]
Actually, we could use an element under ByteSequence.  It would need to be set as a property of the ByteSequence by the parser.  But I think the attribute works better...?

**Comment by nishihatapalmer** [comment]
I've just realised that adding direct support to byteseek to process full DROID syntax for container signatures is not as useful as I thought.

The reason is that, even if that support is there from DROID 6.x, earlier versions of DROID won't understand it.  This means that TNA can't really publish container signatures using the full format, as it excludes everyone who isn't on the latest version of DROID.

This doesn't mean that the whole idea is a non starter, but it does mean that we need a way to transform full DROID syntax into standard PRONOM XML, so all versions of DROID can benefit, and will allow TNA to publish those signatures.

So my proposal is as follows:

1.  I create a DROID syntax compiler, which can process the full DROID syntax.  This will create the right ByteSequence / SubSequence / SideFragment objects from the syntax string.

2.  I add a toXML() method to the above classes, which export the XML definition of those objects in standard PRONOM format.

3.  I add an "expression" attribute to ByteSequence.  If this attribute is present, DROID versions which support that attribute can perform the compilation directly.

The effect of this is that anyone could experiment with creating new container or binary signatures by just adding an expression attribute to a ByteSequence.  Once they are happy with it, they can export the standard XML format with a command line tool (or TNA could do the same).

**Comment by nishihatapalmer** [comment]
It also means that for those who just want to create local signatures and have no intention of having TNA publish them, they can just put the signature in the expression attribute and they're done.

**Comment by jcharlet** [comment]
Hi @nishihatapalmer ,
just spent some time reading your comments and proposal, and even if my understanding is not complete, the whole solution does make sense to me. I discussed it with @Dclipsham who is obviously happy to follow on your advice.
So how shall we proceed? Do you have time to work on this? If so, how can I help? If not, happy to work on it myself. In any case, it would be really helpful to have a conversation with you on it to get up to speed.

**Comment by nishihatapalmer** [comment]
Hi @jcharlet,

I have done some work on this.  I have a parser which parses the full PRONOM syntax, including the additions from container signatures (e.g. single quotes for text, and whitespace between elements).  The parser produces an Abstract Syntax Tree (AST) which is an intermediate representation of the syntax.  I also have a compiler which takes the parser output (AST) and compiles a ByteSequence object from it, creating all the SubSequences and Fragments.

So this lets you feed in a PRONOM syntax string, and get a compiled ByteSequence object out.  I'm now at the stage of testing all of this, and filling in any bits I've missed.  You can see where I'm up to on my fork of DROID in the droidsyntaxparser branch at:

https://github.com/nishihatapalmer/droid

Once that all looks good, it's a matter of wiring it in to the container signatures in some fashion, probably by setting an "expression" attribute on the <ByteSequence> element in the container signature file, which then causes the compiler to be used on it.  End result: you can put full PRONOM syntax into a container.  It could also be used for the normal binary signature files as well  - if you just wanted to add a quick signature to those too.

Any help in testing, coding or documenting would be appreciated!   Maybe have a look at the code in my fork, and then contact me when you know what you're comfortable doing.

**Comment by nishihatapalmer** [comment]
BTW, the code mostly lives in the droid-core project, under signature/compiler.

There are also some code changes required to some of the standard droid signature objects (e.g. ByteSequence) to allow them to be directly constructed with sub-objects, and to provide accessors so that any compiled objects can be tested.

**Comment by nishihatapalmer** [comment]
One thing which would be very useful to do would be to create a toXML() method on the ByteSequence class.  This should just go through the internal ByteSequence objects (SubSequences and SideFragments) and pump out valid PRONOM compatible XML for the ByteSequence object.

This is the other key part of the needed lifecycle, along with wiring in the compiler. The compilation needs a lot of testing, but it's largely there.    Outputting valid XML from a ByteSequence completes the equation, allowing TNA or a user to put in a PRONOM syntax, and then get out the PRONOM compatible XML for it.

**Comment by nishihatapalmer** [comment]
@Dclipsham is there a TNA policy on the minimum DROID version required to support binary signatures published by TNA?   

Obviously, container signatures are only processable by versions of DROID that supported those.  But do we assume that all binary signatures published by TNA are processable by all versions of DROID?

**Comment by DavidUnderdown** [comment]
So far we've basically assumed that everything is completely backward compatible. However, the current endpoint is declared as version 1 I think (or actually we might already be version 2). So one option would be to approach this by creating a new version of signature files - though that would then raise the question as to maintenance, and do we create multiple versions of the signature file for each release.

**Comment by nishihatapalmer** [comment]
It doesn't really do any harm to keep things backwards compatible. We let PRONOM make the XML for binary signatures as normal, but let container signatures get to the same expressive power within DROID.

It is true that container signatures already support some syntax that PRONOM doesn't, such as whitespace between expression elements and ASCII strings in single quotes.  These don't change the fundamental capabilities of the language, they just add some syntactic sugar.  

It would be nice if everything was eventually consistent, but that would require backwards compatibility changes. On the other hand, maintaining both legacy binary and new container syntax isn't that hard, since the new container syntax is just a more convenient way of writing out the expressions in some cases, but doesn't really change anything.

More interesting would be the idea of adding fundamentally new capabilities to the language, such as arbitrary sets of bytes to match, or specifying one or more string encodings to match a string against).  But I think that can wait for another day!

**Comment by nishihatapalmer** [comment]
I've now pushed the first complete support for parsing official PRONOM signatures to my droid fork on the droidsyntaxparser branch here: https://github.com/nishihatapalmer/droid/tree/droidsyntaxparser

It fails to parse four existing signatures, which use constructs that aren't officially supported by DROID.  This is being examined in issue https://github.com/digital-preservation/droid/issues/297 to see what should be done with these.

Next up is testing the compiler stage properly.

**Comment by nishihatapalmer** [comment]
Update: I've now tested against all the container signatures, and there are some constructs in there I need to add support for, such as string literal ranges, e.g. '0'-'9'.  So not yet complete support for binary and container signatures.

**Comment by jcharlet** [comment]
hi @nishihatapalmer 
ok brilliant will be working today and on Thursday on droid, so will check your branch and come back to you.

**Comment by nishihatapalmer** [comment]
Hi @jcharlet ,

great.  I'm also working on DROID, so ping me any questions you like.

**Comment by nishihatapalmer** [comment]
I've just pushed a fully working (as far as I know) parser which handles all binary and container signatures to my droidsyntaxparser branch on nishihatapalmer/droid

**Comment by nishihatapalmer** [comment]
I've now pushed a "works without throwing any errors" compiler, which compiles all binary and container signatures into ByteSequence, SubSequence and SideFragment objects.

I haven't validated it's correct at all - this is just the first version that can handle all of them without throwing an error.

**Comment by jcharlet** [comment]
ok @nishihatapalmer you're going way too quickly on that, while I've been using the day at the office to get the support I needed from Laura and the support team :). 

could you please open a draft PR so that we can track commits on it as well?
I had to make a small correction on my side to compile your code 6171c1dc07c22092a5b3e1a5f5338802cb25a3e3 , but I see you fixed in here https://github.com/nishihatapalmer/droid/commit/d6a2e27b72671657e1dc2682428a863d303c976d


Could you also rebase master on your branch? I have some test failures related to JPA for some reason (even while doing mvn clean test) and as soon as I rebased, it worked perfectly but for your tests below which I thought was normal since you hadn't finished the implementation (was before your very last commits 3h ago).

```
    public void testParsesAllPRONOMSignaturesWithoutError() throws IOException {
    public void testParsesAllContainerSignaturesWithoutError() throws IOException {
```

**Comment by jcharlet** [comment]
or if you'd rather carry on with your working environment and don't bother rebasing, please do, I'll just cherry pick your latest commits like I just did, and you'll be able to cherry pick my own if I do anything that's helpful to you.

**Comment by nishihatapalmer** [comment]
Hi @jcharlet,

I'm not a git expert, sorry - not sure how to rebase master on my branch.  I've updated my master from upstream on nishihatapalmer/droid.  But I'm assuming you want those changing moving up into my actual branch - just not sure how to do that.  Would like to learn how to do this :)

**Comment by jcharlet** [comment]
as mentioned in https://github.com/digital-preservation/droid/pull/304
I created this PR https://github.com/digital-preservation/droid/pull/305 directly from the core repository's branch so that we can both work on it.
