### ISSUE TITLE
Intermittent failure with directory sizing

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/droid#252]
The CI systems show occasional failures with the test `uk.gov.nationalarchives.droid.submitter.DirectoryEventHandlerTest#testDirectoryResultMetaDataWhenDepthOne`:

```
[ERROR]   DirectoryEventHandlerTest.testDirectoryResultMetaDataWhenDepthOne:122 Directory Size is invalid expected:<17680797> but was:<17656054>
```

See https://travis-ci.org/digital-preservation/droid/jobs/579848101

It seems like there is likely a bug with directory size measurement in Droid. For the time being I have disabled this test by setting `@Ignore` so that it doesn't cause problems with other PRs and tests.

**Comment by sparkhi** [comment]
This is fixed as part of PR: https://github.com/digital-preservation/droid/pull/432 
The issue was related to folder size being unpredictable (as mentioned in File class) and we removed recursing to count actual size as it was a performance overhead for not much gain. The folder size is not shown in the UI
