### ISSUE TITLE
How is the {n,*} syntax processed by PRONOM?

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#274]
The document http://www.nationalarchives.gov.uk/aboutapps/fileformat/pdf/automatic_format_identification.pdf defines the syntax for binary PRONOM signatures.

In it, it says you can specify wildcard matches as follows:
```
{m-n}: wildcard matching between m-n bytes inclusive, where m and n are integers or ‘*’.

e.g.: 0x03 {1-2} 4D would match 0x03 3C 4D or 0x03 3C 88 4D. 

e.g.: 0x03 {2-*} 4D would match 0x03 3C 88 4D or 0x03 3C 88 3F 4D
```
Are there actually any signatures that support the second form using the * wildcard?

One way it could work, using the example given above, gives two SubSequences:
```
0x03 {2-*} 4D
```
becomes:
```
SubSequence 1: 0x03 ?? ??
SubSequence 2: 0x4D
```
I've added two ?? bytes - since we're saying there has to be a minimum gap of two between the two SubSequences.

Is this how PRONOM processes such syntax?  Is there an example of one in PRONOM currently?

**Comment by nishihatapalmer** [comment]
This is sort of logically equivalent to rewriting the expression 
```
03 {2-*} 4D
```
as
```
03 {2} * 4D
```

**Comment by DavidUnderdown** [comment]
There appear to be 8 doing {n-*}:

|byte_sequence|signature_id|signature_name_text|
|-------------|------------|-------------------|
|7B5C7274(66|6631)5C(616E7369|6D6163|7063|706361)5C616E7369637067{3-*}5C737473686664626368{1-4}5C73747368666C6F6368{1-4}5C737473686668696368{1-4}5C73747368666269|26|RTF 1.7 - 1.8 (generic)|
|7B5C7274(66|6631){0-15}(616E7369|6D6163|7063|706361)5C616E7369637067{3-*}5C737473686664626368{1-5}5C73747368666C6F6368{1-5}5C737473686668696368{1-5}5C73747368666269*5C(2A5C636F6C6F72736368656D656D617070696E67|6166656C6576|2A5C6461746173746F7265|2A5C646566636870)|522|RTF 1.9|
|7B5C7274(66|6631){0-15}(616E7369|6D6163|7063|706361)5C616E7369637067{3-*}5C737473686664626368{1-4}5C73747368666C6F6368{1-4}5C737473686668696368{1-4}5C73747368666269*5C6C73647374696D6178|523|RTF 1.8|
|4E554D424552204F46205452414345532020203D20[30:39]{3-*}4E554D424552204F46205054532F54524320203D20[30:39]|530|pulse EKKO header file|
|52494646{4}41434F4E{0-*}616E69682400000024000000[!00]*4C495354{4}6672616D69636F6E|571|Microsoft Animated Cursor Format|
|52494646{4}57415645666D7420100000000100{14-*}64617461|606|Waveform Audio (PCMWAVEFORMAT)|
|52494646{4}57415645666D7420[!10]{3}[!FEFF]{16-*}64617461|607|Waveform Audio (WAVEFORMATEX)|
|52494646{4}57415645666D7420{4}FEFF{38-*}64617461|608|Waveform Audio (WAVEFORMATEXTENSIBLE)|

I've only pulled signature name text rather than getting the PUID as it only required a single table join

**Comment by nishihatapalmer** [comment]
Great - thanks for that!

I'm currently working on a parser / compiler to allow container signatures to use the full PRONOM syntax (without having to understand all these arcane details)!

**Comment by nishihatapalmer** [comment]
One thing which would be really useful when researching signatures is if PRONOM could export the actual signatures it holds, not just the compiled XML version.  It's almost impossible to find a signature with particular characteristics using the PRONOM web site, unless you already know it's there.

**Comment by DavidUnderdown** [comment]
We might be able to just do a dump of what's currently there as a csv.

**Comment by nishihatapalmer** [comment]
Final comment - I see how this works now.  It uses the SubSeqMinOffset attribute of the next SubSequence to do this, rather than adding several ?? bytes to the previous one.

So:
```
03 {2-*} 4D
```
becomes
```
SubSequence 1: 0x03 
SubSequence 2: 0x4D      [SubSeqMinOffset = 2]
```

**Comment by nishihatapalmer** [comment]
A CSV dump would be just as useful, to me anyway.

**Comment by ross-spencer** [comment]
PRONOM exports can all be found [here](https://zenodo.org/record/3269467#.XXKTpXUzY5k) in their full and native XML @nishihatapalmer. I was researching your problem earlier and it was easy enough to search across files in a text editor for the results you need.

**Comment by nishihatapalmer** [comment]
Awesome!  I googled around bit didn't find that.
