### ISSUE TITLE
Update email address

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#286]
Need to replace all references to pronom@nationalarchives.gsi.gov.uk with pronom@nationalarchives.gov.uk as the GSI address is no longer in use.

**Comment by jcharlet** [comment]
we will also update copyright year on all headers

**Comment by DavidUnderdown** [comment]
I think I've read it's actually best to express copyright as a range - if you just give the latest date it can potentially cause issues where someone tries to make it look like we've copied their earlier fork...

**Comment by jcharlet** [comment]
oh right, thanks David, @sparkhi please see comment above

**Comment by sparkhi** [comment]
Sounds good. I'll change them into a range as whatever is existing - 2020 (e.g. 2016 would change to 2016 - 2020)

**Comment by Dclipsham** [comment]
see also #180 - beware of breaking builds with updates the copyright status cc @adamretter

**Comment by jcharlet** [comment]
adding an automated year range for the copyright requiring a bit more effort than expected. not planned here finally.

**Comment by jcharlet** [comment]
> see also #180 - beware of breaking builds with updates the copyright status cc 

@Dclipsham the issue there was because someone tried to put a year in a file header different to what the license plugin is checking against, it has to be consistent across all files.

if we produce any breaking change like this, it would prevent travis to build our branch,  and we'd get a notification in the pull request, so no way we can miss it.
