### ISSUE TITLE
Wildcards (?? * {n}) not being matched in DROID container signatures

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#50]
Developing OLE2 based signatures I have discovered that DROID isn't matching signatures it should using various wildcard components. 

I base my research around Thumbs.db files. 

Thumbs.db files are OLE2 based objects. As such, they can be sent through to the container recognition mechanism in DROID 6.1.3.

Their structure is:

```
Thumbs.db
   - 1
   - 2..n (images stored in Thumbs.db)
   - Catalog
```

The numbered files and 'Catalog' sit at the root level, and there are no additional files or folders. These files do not have an extension.  

I am able to get a simple container signature working by just looking for 'Catalog'. Further, I can get it to match a basic byte sequence in the object: 10 00 07 00

However, I can't get it to match longer, more variable byte sequences using various regular expression components. For example:

```
10 00 07 00 ?? 00 
10 00 07 00 {1} 00 
10 00 07 00 * 00 
```

Do not match. 

The wildcard represents the number of image files stored inside the Thumbs.db file. For the minute I can't verify which additional bytes it will use for larger numbers.

For now I can use the workaround:

```
10 00 07 00 [00:FF] 00 
```

Or just truncate the signature.

It would be preferable to use the alternative patterns for greater expressiveness. Other users might require them for different signatures. I also understand that there is an impact on performance of certain wildcards. 

The remainder of my complete Thumbs.db signature will likely use another single byte wildcard and a double byte wildcard. 

In support of this issue ticket I have a similar write-up, and supporting files on the DROID-list Google Group: https://groups.google.com/forum/#!topic/droid-list/0xDnputieUk

DROID version used: 6.1.3
Signature files: Custom

**Comment by nishihatapalmer** [comment]
Hi Ross,

DROID doesn't yet support *parsing* wildcards in the main sequence of the XML.  If you look at how they are constructed generally in the binary signatures, you have to split up sequences with wildcards into a main subsequence of straight bytes, with ? wildcard parts represented as fragments.  * wildcards are represented as additional subsequences.

For the ? example, in the XML you would need a ByteSequence with a Sequence of "10 00 07 00", which then had a RightFragment, offset by one, of "00".  

This was the result of the original (unfortunate IMHO) decision to make PRONOM parse the signatures and supply the broken down signatures to DROID - a spec for DROID to create its objects.  A shame, because Java code is more suited to parsing text than a database is, and it would make creating new signatures without access to PRONOM much easier.

Something to look at in future I guess... I've been thinking about building in more smarts to the DROID signature processing, so external parties aren't reliant on PRONOM to create the signature specs.  Much nicer to just give a regex like signature in one string and have DROID deal with it...

cheers,

Matt

**Comment by nishihatapalmer** [comment]
I just announced droidSig - a utility to convert DROID regular expressions into <ByteSeqence> XML, for pasting into a signature file when testing new signatures.  Makes it much easier to test new signatures.

Details are in a new ANNOUNCE post in this group.

**Comment by paulyoung84** [comment]
This issue has been added to the DROID backlog, it will be assigned an appropriate priority but is unlikely to be included in the next release.

**Comment by ross-spencer** [comment]
Duplicate of https://github.com/digital-preservation/droid/issues/237
