### ISSUE TITLE
SIARD 2.1 identified as ZIP

### ISSUE THREAD

**Issue by sfa-siard** [digital-preservation/droid#546]
Hello

We noticed that if we unzip and rezip SIARD files (and rename them as .siard), they aren't identified as SIARD files anymore. The reason we do this, for example, is to convert the file formats in LOBs as a preservation action.

I attached a test file which was originally created with SIARD Suite. You will also find two deriviations, one where I unzipped and rezipped it with IZArc, the other with 7zip. In addition, I added the DROID file where you can see that the original is correctly recognized as SIARD while the two deriviations are identified as ZIP.
 
[SIARD-test-files.zip](https://github.com/digital-preservation/droid/files/5552259/SIARD-test-files.zip)

**Comment by Dclipsham** [comment]
Hi there, thank you for your enquiry.

In order to identify a file as SIARD 2.1, DROID is searching for the path: 'header/siardversion/2.1/' relative to the root of the zip file, which is what we see in the original SIARD file within the zip you've attached.

In the other two zip files, there's an additional directory in the hierarchy called 'oracle_hr_scott', which means that the 'header' directory is no longer at the root of the zip file. Presumably oracle_hr_scott was the name of the original SIARD file?

From my reading of the SIARD 2.1 specification (https://github.com/DILCISBoard/SIARD/blob/master/SIARD%202.1/format/2018-02-15/siard_2.1_format%20description.pdf Section 4.2) it seems that the 'content' and 'header' directories must be at the root of the zip and no other directories are permitted at this level, so it would appear that the 'round trip' to replace the LOBs has resulted in an non-comformant SIARD file.

The 7zip documentation provides an example of how to add the contents of a driectory to an archive without including the top level directory itself: https://sevenzip.osdn.jp/chm/cmdline/commands/add.htm (I haven't verified this process, but it looks like it should achieve the desired outcome). 

I hope this helps.

David

**Comment by sfa-siard** [comment]
Hi David

Thanks for this. It hadn't occured to me that I was adding an extra folder and messing up the SIARD. You are right that oracle_hr_scott was the name of the original file.

I did a second round of tests making sure that I got it right with the folders this time. I created four tests files, unzipping the original file with both 7zip and IZArc and rezipping both of the folders with 7zip and IZArc. The two files which were zipped with 7zip were recognized by DROID, the two files zipped with IZArc however are still identified as ZIP files. You can find my test files and the DROID output here:
[SIARD-test-files-2.zip](https://github.com/digital-preservation/droid/files/5568990/SIARD-test-files-2.zip) 

I'm curious to see if you will find another simple error which I overlooked.

Christa

**Comment by Dclipsham** [comment]
Hi Christa,
The two IZArc-zipped files are failing to correctly identify for me too. Upon inspection, I can see the the directory '2.1' is missing from the 'siardversion' directory in both, but it is present in the 7-zipped files. I wonder then if IZArc is quietly discarding empty directories. 

Looking the the changelog for IZArc (https://www.izarc.org/news) I see a line on the Version 3.6 Build 1260 notes that says "-Added support for store empty subfolders" Are you using a later version, and if so, can you see an option within IZArc to store empty subfolders? I'm afraid I'm not familiar with the software myself...

David

**Comment by sfa-siard** [comment]
Hi David 

I think you are right in that IZArc is discarding the empty directory. 

We use version 4.4, but I wasn't able to figure out a way to keep empty directories. I guess, we'll just stick to 7zip in the future when manipulating SIARD files. 

Christa
