### ISSUE TITLE
PDF/A-2u not recognised as such, instead only as PDF 1.7

### ISSUE THREAD

**Issue by oschihin** [digital-preservation/droid#573]
Hi

We seem to have stumbled upon an issue that I guess is not a first. We have many PDF-documents who have been converted to the archival standard PDF/A-2u (fmt/478). When validated with Callas, PDF-Tools or in Kofax Power-PDF, they are said to be valid PDF/A-2u. Still, when identified with DROID, we are told they are only PDF 1.7 (fmt/276).

Searching for anything helpful I found the tool [Siegfried](https://github.com/richardlehane/siegfried) that also uses PRONOM signatures for file identification. In that tool, theses files are correctly identified as fmt/478.

When I open the files in a text viewer / hex viewer, I see the correct header value:
```
%PDF-1.7
```

Near the end of the file, I find the RDF-formed "A"-declaration:
```
    <rdf:Description xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/" rdf:about="">
      <pdfaid:part>2</pdfaid:part>
      <pdfaid:conformance>U</pdfaid:conformance>
    </rdf:Description>
```

Any ideas? Does DROID stop on finding a version and not parse the full file? Or is the signature file incomplete?

Thanks for help

**Comment by Dclipsham** [comment]
Hi Oliver, thanks for raising this. 

Out of the box, DROID is set to scan the first and last ~64k of the file for matches. It sounds like, with your file containing the correct elements appearing near the end of the file, that DROID is still set to this, particularly since Siegfried is giving the correct ID outcome.

Within DROID, under Tools > Preferences you should see an input box for 'maximum bytes to scan'. If you set this to a negative value, e.g. -1, then click OK to save your changes. You'll be returned to the main DROID screen. Next, select 'New' as this will create a new profile with the modified settings applied, then re-run your DROID scan. This should now give the expected identification outcome. Do let me know if it doesn't though!

I hope this helps.

David

**Comment by oschihin** [comment]
Hi

Thanks a lot, minor config issue. It seems to work. I'll check that option next week on our server installation and will report back and close then.

Oliver

**Comment by oschihin** [comment]
It works, thanks, I'll close.
