### ISSUE TITLE
jar version in droid.sh out of date wrt pom.xml

### ISSUE THREAD

**Issue by eliotstock** [digital-preservation/droid#73]
I had to edit droid.sh in order to run DROID after a build:

6.1.5 -> 6.1.6-SNAPSHOT

Use a wildcard for the jar path instead?

**Comment by snail1966** [comment]
Yes this will be the case if you build from the GitHub source due to the auto-incrementing behaviour of the Apache Maven build software (the same applies to the .bat for the Windows version).  The current release version (http://www.nationalarchives.gov.uk/information-management/manage-information/preserving-digital-records/droid) will always contain the correct paths.
Regards, Brian
