### ISSUE TITLE
Command line -A not working as expected in DROID 6.6 RC

### ISSUE THREAD

**Issue by tnafrancesca** [digital-preservation/droid#876]
When typing the command  '-Nr "path to folder or single file" -Ns "path to signature file" -A ' not all archive files are opened or shown in comparison to typing the same command over the same set of test files in DROID 6.5.2. Command line results in attached file.
[User_testing_94_DROID_Command_Line_Issue.txt](https://github.com/digital-preservation/droid/files/10536901/User_testing_94_DROID_Command_Line_Issue.txt)

**Comment by sparkhi** [comment]
It looks like the -A command is working fine, except, the xlsx files used to be expanded on CLI in 6.5.2 and they are not anymore

**Comment by steve-daly** [comment]
Thanks @sparkhi 
@tnafrancesca - could you retry your test inhibiting expanding of archives using the -At switch instead of -A.  It might be that both variants on 6.6.0 are actually expanding archives but the lack of URIs make it difficult to see that.  

the change in behaviour may be that in 6.5.2, the default was to not expand archives whereas in 6.6.0 the default is to expand them.  I think this would be a breaking change for some users so we should look at that.

**Comment by sparkhi** [comment]
This is fixed in 6.6.0
