### ISSUE TITLE
In no profile mode in new DROID 6.6 full file paths not showing

### ISSUE THREAD

**Issue by tnafrancesca** [digital-preservation/droid#877]
When typing the command '-Nr "path to folder or single file" -Ns "path to signature file" -A ' the full file path is not shown in DROID 6.6 Release Candidate  but do in DROID 6.5.2. I'm not sure if this is intentional. Results from the command line attached
[User_testing_94_DROID_Command_Line_Issue.txt](https://github.com/digital-preservation/droid/files/10536934/User_testing_94_DROID_Command_Line_Issue.txt)

**Comment by paulwellsagilej** [comment]
@nishihatapalmer Between 6.5.2 and now 6.6.0 the format for listing results has changed. There are two approaches to resolve this: 1, compare the two versions and find the point where the behaviours diverge, 2, update the code to force it produce the output which is expected. I have spent some hours on option 1 but there are a great many changes affecting code and configuration. Option 2 is simple provided we have a crisp definition of the output. Please can you advise if the change in behaviour for container files was intentional?

**Comment by steve-daly** [comment]
Hi @paulwellsagilej what did you mean about change in behaviour for container files?  Is this where we noticed the handling of xlsx files was different, as that's entirely undertsadable as v6.6.0 can use the container signature defaults and therefore identify xlsx properly rather than treating them as zip.  

It's also fine that the first few lines of v6.5.2 No Profile mode output are missing in v6.6.0, and that's a positive improvement.  

And I believe we know how to revert the default so that Archive files are not expanded unless the -A switch is provided.  To match the behaviour of v6.5.2. 

But it's mainly the full path output that's missing in v6.6.0 and just the filename being shown, which makes it difficult to act upon the results especially where the same filename appears in different subfolder.  Is that the only thing you're looking at here?

**Comment by paulwellsagilej** [comment]
@steve-daly That's change in behaviour as in change in output listing format. If you can supply a definition of the required behaviour and the acceptance criteria I will make a pull request with the necessary changes.

**Comment by steve-daly** [comment]
Thanks @paulwellsagilej - I just wasn't sure what you were referring to when you say "change in behaviour for **container files**".  I think the row output syntax is different for all all source files rather than a subset.

**Comment by nishihatapalmer** [comment]
It should be easy to output the full path instead of just the file name, if that is what is required.  

I don't think it has anything to do with container files particularly (other than it may identify them as container files rather than zips, as Steve says).

**Comment by tnafrancesca** [comment]
Sorry everyone- I think when I submitted the pull request I may not have explained the issue properly.
So I believe what @paulwellsagilej means by 'container files' is 'archive files'? So when we unzip rar, zip, gzip ect. Of course sometimes a zip or an OLE-2 will later identify with a container signature but that is a different thing all together.

The main issue was  there is a difference in how the results are presented. In DROID 6.5.2 the command results show like this per line 'rar:\\\na-stor01\homedir$\fmackenzie\Desktop\DROID_Testing\archives\custom sample.rar!\LongDirWithCamelCaseName\fmt-144-signature-id-692.pdf,fmt/144' (please ignore the triple \\\ if I'd put the files in the right place it would be starting with C:), in DROID 6.6.0(RC2) each file shows as 'fmt-144-signature-id-692.pdf,fmt/144' so we are missing the type of archive file being opened (zip, rar ect.), and the file path.

I think the first question really is do we prefer the output from DROID 6.5.2 or DROID 6.6.0(RC2). Is this an intentional improvement. It has some advantages and seems much tidier to look at but also provides less information.

The other question is if we want to go for back to the DROID 6.5.2 output then from how I understand it there seems to be two decisions. Whether to try and go through the code changes and work out in the commit history where this happened to  reverse it. The pros being it is less likely to affect anything else in DROID.
Or the second option is to just write some new code that will be a quick fix if going through the commit history will take too much time. I know that some time has already been spent on it.

Is that a good summary of the situation?

**Comment by DavidUnderdown** [comment]
Just a quick note on the interaction with csv-validator. The URLs beginning with rar etc (rather than being a true file:/// URL) is quite useful as csv-validator cannot do a fileExists or checksum check on the files within an archive (it can check the outer archive container itself of course) and having the different start makes it relatively easy to exclude entries which don't start file: from the checks). Which is a rather long-winded way of saying that I like the 6.5.2 behaviour!

**Comment by Dclipsham** [comment]
just to remind that any changes to the format of output text generally could be breaking for downstream consumers of DROID (including your own in TDR & DRI) so please do treat them with care and consider putting radical changes behind a feature flag. 

In the above case as illustrated with Francesca's text file the absence of full filepath would very likely be problematic

**Comment by nishihatapalmer** [comment]
My goal in the  no profile mode for the latest droid was that it should be as close as possible to the previous version.

If it is now different then we should try to make the output look like the previous version.  It certainly wasn't at attempt to make things look tidier.

**Comment by nishihatapalmer** [comment]
Yes, an API would be great.  In fact, the recent changes to the command line move in that direction as there is now a single unified code base for recognition.  Previously the command line reimplemented large parts in a slightly different way to the GUI so results and processing  were inconsistent.  It would be possible to wrap the core processing in a simple API now without much difficulty.

It might be an idea though to be clear about what is supported from a backwards compatibility perspective.  Scraping console output should never be relied upon in my opinion, this will always be fragile to some extent.  Processing the CSV output would be more reliable.

**Comment by sparkhi** [comment]
The original issue about full path is fixed in 6.6.0
