### ISSUE TITLE
RTFs sometimes recognized only as octet-stream

### ISSUE THREAD

**Issue by tballison** [digital-preservation/droid#94]
There were roughly 90 files that Tika identified as RTF but DROID identified as octet stream.  I'm attaching two examples.  File names are the digest id from Common Crawl.
[rtfs.zip](https://github.com/digital-preservation/droid/files/316543/rtfs.zip)

**Comment by snail1966** [comment]
Thanks for raising this - do you have any further info about the DROID version, signature file version etc. you were running when you got the octet stream results? When I ran this in the latest DROID release (GUI version) I got no identification at all with the default options, but 5 identifications by extension (none by signature) when I enabled the "Match extensions against all know extensions" option in the Preferences.  i.e. as follows:

fmt/355	Rich Text Format	1.9	application/rtf, text/rtf
fmt/45	Rich Text Format	1.0-1.4	application/rtf, text/rtf
fmt/50	Rich Text Format	1.5-1.6	application/rtf, text/rtf
fmt/52	Rich Text Format	1.7	application/rtf, text/rtf
fmt/53	Rich Text Format	1.8	application/rtf, text/rtf

From an initial look , it appears that this may be related to the fact that some signatures for RTF (e.g. fmt/355 - Signature ID 522) have multiple fragments - a similar issue has been identified elsewhere so will need to investigate further and see if there is any connection.  It seems this issue only affects certain files, but not others.

**Comment by tballison** [comment]
I was using the nanite wrapper (probably 1.3.1-84 which used droid 6.1.3).  The only configuration was `.setMaxBytesToScan( -1 )` When I did the run, there were no file extensions on the files.  I added those to make it easier to double-click to open...sorry.

**Comment by snail1966** [comment]
I've looked further at the two sample files supplied, using the current DROID signature file (v. 88).
I had thought that this might be related to multiple occurrences of fragments (cf. issues #82 and #104) since the RTF signatures have multiple fragments. However this is not the case.

Rather, it turns out that the samples do not match any of the RTF definitions in the current DROID signature file.  The following is a detailed explanation:

Analysis of sample file JSHZR2ROORGUPFRA6MVZUVIJUIHZOJTE.rtf :

fmt/355 (ID 1101)  rtf 1.9, signature ID 522:
- the byte sequences 5C616E7369637067 and  5C737473686664626368 do not occur in the file.

fmt/53 (ID 753), rtf 1.8, signature id 523
the byte sequences 5C616E7369637067, 5C737473686664626368 and 5C6C73647374696D6178 do not occur in the file.

fmt/52 (ID 633), rtf 1.7, sig. ID 26 
the byte sequences 5C616E7369637067 and 5C737473686664626368 do not occur in the file.

fmt/51 (ID 632), rtf 1.6.  No signatures defined.

fmt/50 (Sig 631), rtf 1.5-1.6, Sig. ID 158
The byte sequence 5C616E7369637067 does not occur in the file.

fmt/49 (ID 630), rtf 1.4 ; fmt/48 (ID 629), rtf 1.3 ; fmt/47 (ID 628), rtf 1.2 ; fmt/46 (ID 627), rtf 1.1
No signatures defined

fmt/45 (ID 626), rtf 1.0-1.4, Sig. ID 30
The byte sequence 7B5C7274 is found in the file.  So are the initial right fragments 6631 and 5C at the expected offsets. However the remaining fragments are not found in the file.

fmt/969 (ID 1774), rtf 0, Sig. ID 1333
The byte sequence 7B5C727466305C does not occur in the file.

For the other sample file JSHQU7XROWPZZNYZVOGTVHMQMGQRTZPW.rtf,  explanations for fmt/46. fmt/47, fmt/48, fmt/49, fmt/50, fmt/51, fmt/52, fmt/53, fmt/355 and fmt/969 are as above.
For fmt/45, the main byte sequence 7B5C7274 is found, and then the 1st right fragment 6631.  However, this is then followed by 7B, not 5C as expected.  The following byte is 5C but it is required to be at an offset of 0, not 1 from the previous fragment - hence the attempted match will fail at this point.

**Comment by Dclipsham** [comment]
Nothing to fix
